const express = require("express");
const AuthController=require("../Controllers/authController");
const { HandleErrors } = require("../middlewares/handleError");
const authRoutes = express.Router();
authRoutes.get("/login", HandleErrors(AuthController.userLogin));
authRoutes.get("/OTPSignup", HandleErrors(AuthController.OTPSignup));
authRoutes.get('/checkphone',HandleErrors(AuthController.checkPhone));
authRoutes.get('/forgotpass',HandleErrors(AuthController.OTPforgotPass));
authRoutes.get("/OTPVerify", HandleErrors(AuthController.OTPVerify));
module.exports={authRoutes};
